amazonProperties:
  endpointUrl: ******************************************
  accessKey: ******************************************
  secretKey: ******************************************
  bucketName: ******************************************
  app_client_id: ******************************************
  user_pool_id: ******************************************
  
  multipart:
    maxFileSize: 10Mb
    maxRequestSize: 10Mb